[package]
name = "minigrep"
version = "0.1.0"
authors = ["Andi Aqil A <40452321+atriple@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
